anchor_version = "0.28.0"
solana_version = "1.16.12"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.localnet]
smart_wallet = "3V3UUik5YwwVc52cUsEgWKfXPJktcdcoxyFK1tcYLLVt"
govern = "9NwSsrDnRHki6YLJsejccdx2Bu5JUn1fMYdoyPZ1ZtMu"
locked_voter = "HfPBCZ4QxAXRLkvPBWJL2xtfmLKXcZfbNv7oUagWsxTi"
